### PR TITLE
Added support for executing ruby

### PR DESCRIPTION
**Pull request by andersjanmyr**
Ruby is exposed via a /eval_ruby method on the sinatra app.
Not very safe, but what the hell, it is a presentation. :)

### CODE REVIEW

**Comment by schacon** [comment]
since i push this to heroku, i can't really do this. i would need some way to turn it off or something

**Comment by andersjanmyr** [comment]
I added a check for the SHOWOFF_EVAL_RUBY environment variable, will that do?

**Comment by schacon** [comment]
cool

**Comment by schacon** [comment]
haha, tricky.  i noticed this when evaluating the merge, but the downcase pull request commit was in the history of this one, so it closed them both when i pulled this in. well played.

**Pull request merged**
