### PR TITLE
Add ability to skip individual slides

### PR DESCRIPTION
**Pull request by rafmagana**
Sometimes one wants to see how the presentation looks like without some slides (mostly when we are uncertain about keeping slide or not) but one don't want to delete them, here's an example:

```
!SLIDE bullets incremental transition=fade skip

# Bullet Points #

* first point
* second point
* third point
```

what do you think?

### CODE REVIEW

**Comment by goncalossilva** [comment]
I like this. I'm not sure if skip is better than ignore, but it's not really that important.

We're in the middle of a big discussion at PR #184. Maybe @burtlo could take a look at this and merge it with his branch?

Thanks!

**Comment by goncalossilva** [comment]
A note about this on the README would be pretty cool, too.

**Comment by rafmagana** [comment]
Are you talking about this? https://github.com/rafmagana/showoff/commit/81a5669bd209b2d0abd403a53b94def19f8a7b85#diff-0

**Comment by goncalossilva** [comment]
Yes. I have no idea how I missed that.

**Comment by burtlo** [comment]
I will definitely add this feature to the branch I have created.

**Comment by rafmagana** [comment]
@burtlo are you gonna use my commits or make the change yourself? Thanks anyways

**Comment by burtlo** [comment]
Most of the work on the branch is vastly different. So I will have to interpret and write the changes myself.

**Comment by goncalossilva** [comment]
`git commit --author="Rafael Magana <rafmagana@gmail.com>"` works, too :)

**Comment by rafmagana** [comment]
That would be awesome, but I can add that functionality after your commits gets merged too. What do you think, @burtlo ?

**Comment by burtlo** [comment]
@rafmagana currently the state of slide metadata has a poor implementation to support this feature.

I've updated the current implementation of [Metadata.parse](https://github.com/burtlo/showoff/blob/master/lib/showoff/metadata.rb#L25) to use a list of [parsers](https://github.com/burtlo/showoff/blob/master/lib/showoff/metadata.rb#L37), which are simply classes that define the format of the metadata that is being captured.

Right now, there is no formal parsers registration, it's simply an entry in that list of classes.

So, if you would like to implement this functionality in the current setup I have you would:
- Define a file in the `lib/metadata` folder, require it in the `lib/metadata.rb` file
- Add it into the order of parsers, likely before `CSSClasses`, as that one swallows all terms to be CSS classes.
- Add an attr_accessor for the skipping/ignoring

Then for the slide to be ignored/skipped, you will need to decide:
- Do you want to have the slide ignored from the start, when it is parsed?
  
  > Then you want to update the [MarkdownSlideSplitter](https://github.com/burtlo/showoff/blob/master/lib/showoff/parsers/markdown_slide_splitter.rb) to simply not add slides with that metadata.
- Do you want the slide to be included but simply not rendered?
  
  > Then you want to likely create a new  [post renderer](https://github.com/burtlo/showoff/blob/master/lib/showoff/slide.rb#L100) that could be initialized with the current state in the metadata and simply returns `nil` content. That will remote the content and that empty slide should be removed when the html content is `compact`'d and then `join`'d.

**Comment by rafmagana** [comment]
@burtlo Cool, I will check your code out and add the functionality, should I fork your code and make a pull request to your repository? or how do you recommend me to do it?

**Comment by burtlo** [comment]
Yes, @rafmagana fork my code and send me a pull request. That would be awesome!

**Comment by rafmagana** [comment]
@burtlo ok, I will do it as soon as I have time, thanks!

**Pull request merged**
