### PR TITLE
Copy all needed js/css/image files to static dir

### PR DESCRIPTION
**Pull request by badboy**
`showoff static` now produces a real, ready-to-run-everywhere presentation.
I needed this for two presentations and it really bugged me to fix the paths manually.

With this patch you can take the _static_ dir, drop it on a usb stick and show the presentation on whatever computer is near including all images, custom styles and javascript code you wrote.

### CODE REVIEW

**Comment by rctay** [comment]
Thanks for this. I'm currently using [a Makefile to do the copying](https://github.com/rctay/nus-hack-vcs/blob/build/Makefile), which is clearly suboptimal.

**Comment by schacon** [comment]
i'm having some issues with the JS.  i pulled it in because it's much better than what was there, but it's not advancing the slides, so it's not in 0.3.3.  let me know if it works for you as i've pulled it.

**Comment by badboy** [comment]
What exactly do you mean?

**Comment by schacon** [comment]
pressing any buttons does not advance the slides for the example preso - i'm stuck on slide 1.  i'll dig into the JS to see why, but it's not working for me yet.

**Comment by badboy** [comment]
latest `git pull`-ed `showoff static` seems to work just fine with my two presentations.

**Comment by badboy** [comment]
I did not change any of your javascript. Maybe some custom javascript blocking the events?

Edit: Ah! Ok. Just tested it with the example preso. Same bug here, will look into it now.

**Comment by schacon** [comment]
oh, i see what it is.  the syntax highlighting code is loaded dynamically based on what languages are needed and that ajax call is not allowed from a file:// URL because of how the URL is constructed.  if you have syntax highlighted code in your preso, it looks like this will break.  however, if you run some static server (like jekyll or something) it works great - which is cool, because that means it will work from a gh-pages branch or something.  Love it.  Thanks!

**Comment by badboy** [comment]
So do we leave the code as it is or should I build some work-around to disable syntax highlighting in static presenations by default?

**Comment by schacon** [comment]
it certainly doesn't bug me enough to fix it ;)

**Comment by badboy** [comment]
A quick solution would be this small patch:

```
diff --git a/public/js/showoff.js b/public/js/showoff.js
index a1a2078..b7d0f4d 100644
--- a/public/js/showoff.js
+++ b/public/js/showoff.js
@@ -85,7 +85,7 @@ function initializePresentation(prefix) {
        slidesLoaded = true
    }
    setupSlideParamsCheck();
-   sh_highlightDocument(prefix+'/js/sh_lang/', '.min.js')
+   location.protocol == "file:" || sh_highlightDocument(prefix+'/js/sh_lang/', '.min.js')
    $(".preso").trigger("showoff:loaded");
 }
```

This way the highlighting is only executed if the file is served by a server

**Pull request merged**
