### PR TITLE
Fixed the swipe events to not skip many slides

### PR DESCRIPTION
**Pull request by andersjanmyr**

### CODE REVIEW

**Comment by badboy** [comment]
hm, now that I see your pull request, I remember to clean up mine: https://github.com/schacon/showoff/pull/65/
Mine does the same to not skip slides and adds the possibility to use a tap to advance slides.

**Comment by andersjanmyr** [comment]
Ah, I missed yours, I would have used that instead. We'll see which one Scott pulls :)

**Comment by schacon** [comment]
i pulled #65.  sorry about that. i owe you a :beer:

**Comment by andersjanmyr** [comment]
That's cool, anything that works :)

**Pull request closed without merging**
