### PR TITLE
Fix for presenter view on Firefox (issue 167)

### PR DESCRIPTION
**Pull request by durin42**
Also includes a second commit to clean up some trailing whitespace. Not passionate about that one, feel free to drop it if you don't want that change.

### CODE REVIEW

**Comment by goncalossilva** [comment]
Doesn't this cause issues with other browsers? I'm asking naively, I didn't test it.

**Comment by durin42** [comment]
I tested Safari, Chrome, and Firefox. They all looked reasonable.

**Comment by durin42** [comment]
That said, feel encouraged to check my work before merging. I'd hate for it to be a "works on my machine" situation.

**Comment by durin42** [comment]
So, presenter view still looks good in Chrome and Safari, as well as (now) FireFox.

**Comment by goncalossilva** [comment]
Finally got around to checking it out. Thanks!

**Pull request merged**
