### PR TITLE
reset preso width after going full-page

### PR DESCRIPTION
**Pull request by justone**
If you have a single slide that's full-page, the next slide doesn't get centered properly.  This patch re-centers the #preso element.

### CODE REVIEW

**Comment by benjmin-r** [comment]
Tested and works well ... thanks for providing this fix ... apart from that: +1

**Comment by shamansir** [comment]
In my case it failed (I play with different sides of slides, not just `1020px` and my `preso` block becomes narrower than slide), in my case this helped:

```
if (fullPage) {
    $('#preso').css({'width' : '100%', 'overflow' : 'visible'});
    currentSlide.css({'width' : '100%', 'text-align' : 'center', 'overflow' : 'visible'});
} else {
    currentSlide.css({'width' : '100%', 'overflow' : 'hidden'});
}
```

**Comment by grundprinzip** [comment]
I'm not sure about this, but I think the best solution would be to reset the custom style applied to the #preso element and make it inherit the value from the base stylesheet. I'm no real CSS and jQuery Guru, but what combines both solutions best would be

``` javascript
if (fullPage) {
    $('#preso').css({'width' : '100%', 'overflow' : 'visible'});
    currentSlide.css({'width' : '100%', 'text-align' : 'center', 'overflow' : 'visible'});
} else {
    $('#preso').css({'width' : '', 'overflow' : ''});
}
```

I'm happy for comments on the matter of resetting the stylesheet or other ideas :)

**Comment by goncalossilva** [comment]
I'm merging this and changing it to @grundprinzip's proposal, it's more flexible and works perfectly. Thanks!

**Pull request merged**
