### PR TITLE
Slight changes for GLI 2

### PR DESCRIPTION
**Pull request by davetron5000**
When I gem install'ed showoff, I got GLI 2, even tho the gemspec specifies a 1.x version.  At any rate, I figured I'd update this executable, so now it should work with the latest GLI.

### CODE REVIEW

**Comment by afeld** [comment]
+1

**Comment by joejulian** [comment]
+1

**Comment by lab360** [comment]
+1

**Comment by barraponto** [comment]
+1

**Comment by joejulian** [comment]
I've merged this and several other unmerged pull requests into my fork.

**Comment by barraponto** [comment]
@joejulian it seems @puppetlabs has been mantaining a fork for a while. Would you create pull requests there?
We definitely need a canonical fork. @schacon should help point the successor to this repository as well.

**Comment by joejulian** [comment]
I'm heading down to puppetlabs on Friday. I'll ask around and see if they're interested. My impression was just that they forked it just for their internal use and so they could change the favicon.

**Comment by davetron5000** [comment]
If github isn't spending part of it's 100M on maintaining showoff, I have to wonder what the heck they are doing over there :)

**Comment by binford2k** [comment]
We are putting together a pull request for @schacon to merge. But if he's wanting to hand it off, we'd be happy to maintain it.

This fix is already in our fork, btw.

**Pull request merged**
