### PR TITLE
Add tap to advance slides, timer prevents from advancing too far.

### PR DESCRIPTION
**Pull request by badboy**
Added a binding to the tap event and extended the swiperight/swipeleft functions to prevent execution within a small time boundary. This way it's executed only once, even on a long swipe. Works just fine on my Nexus One with the example preso.

I hope the retabbing is ok. If not, I will re-send this pull request without the retabbed file.

Closes issues [57](https://github.com/schacon/showoff/issues/#issue/57) and [62](https://github.com/schacon/showoff/issues/#issue/62).

### CODE REVIEW

**Comment by badboy** [comment]
Oh, last two commits were not really related to the initial pull request but as they are just some small bugfixes I leave them in.

**Comment by schacon** [comment]
did i have mixed tabbing in the file? or are you just switching it from 2-space to tabs?

**Comment by badboy** [comment]
Hm, it seems there is just one line indented with spaces in your version of the file, all others are indented by tabs. As I prefer tabs I switched to spaces only.
If you prefer tabs, I will remove the commit from this pull-request.

**Comment by badboy** [comment]
closed in favor of #80

**Pull request closed without merging**
