### PR TITLE
Templating + Fixes for Static and PDF Generation

### PR DESCRIPTION
**Pull request by grundprinzip**
Hi,

basically this group of commits does a few things. 

First, it implements a way to provide the user with layout templates if he wants and make the pretty configurable . Templates can be applied either per default or per slide. Please have a look at the updated readme for a usage instruction.

Second, I fixed a a few bugs that relate to static HTML and PDF generation. This includes, rewriting URLs used in CSS to point to static file:// URIs, forcing wkthmltopdf to use the print media styles instead of the screen media styles. In addition sytnax highlighting now works both in PDF and static mode.

It would be great if you could review my changes. 

You can find a simple presentation of how to use the templates, made with showoff here - http://grundprinzip.github.com/Showoff-Templates

Thanks
Martin

### CODE REVIEW

**Comment by grundprinzip** [comment]
This would close #143 and #144 as well.

**Comment by grundprinzip** [comment]
I merged the recent changes from schacon/master to keep the changes compatible with the current development.

**Comment by bowsersenior** [comment]
Hey, this is just what I was looking for! I hope this gets merged in soon.

**Comment by goncalossilva** [comment]
I love this change. I'm not so sure about the ~~~ SYNTAX ~~~, but I don't have a better suggestion either.

I'll merge this and tweak the README a little bit. This is an advanced feature and I believe it's introduced too soon.

**Pull request merged**
