### PR TITLE
I'm all strung out and really want to merge my fork bad, man

### PR DESCRIPTION
**Pull request by alexch**
Scott - Please look over my changes and let me know which ones you approve of and which you have problems with. I'll do whatever you ask (within reason and the laws of the State of California) to improve them or split them up into bite-sized chunks.

Here's an email I sent to  a few weeks ago. Did you get it?

showoff.json: 
  allow single files as sections; allow mere strings instead of {section: name} in showoff.json
  if filename starts with '#' it's not a file name, it's raw markdown
  if there's no showoff.json file, just use ./*.md in alphabetical order

default style:
  better pre padding (in case you want to give it a color background)
  blockquotes and numbered lists are better
  pre nested inside li was super-big
  give 'normal' lists more list-like styling (bullets, left margin). Use plain paragraphs for centered text.
  improve CSS for nested bullet lists, subsection titles
  CSS changes (nested lists are bulleted; plain text isn't tiny)
  make small bullets more legible

misc:
  don't inline sh_lang languages... not sure why
  minor fix to triggered events
  every H1 creates a new slide (unless it's already on a new slide)
  incremental mode uses visibility:hidden rather than display:none, so visible elements stay where they were, and so resizing works on incremental slides
  bugfix in new slide code
  allow a few spaces before the '@@@' to make code blocks easier to write
  bugfix: stop using gemspec directive, since showoff.gemspec loads stuff that's not necessarily there yet
  added ? as an alias for toggle help; updated help box to include most key commands
  pres_file option which  to override the name of the 'showoff.json' file, to allow several different presentations which share sections
  'showoff serve' can take an argument to specify presentation directory

Are there any you disagree with? I'd love to get in sync with you so I can just tell my students "gem install showoff" instead of complicated git clone / rake / install instructions...

Some of these are from the "presdir" branch
https://github.com/schacon/showoff/pull/88

Others are from my master branch. I just rebased so it should be easy for you to merge. Tell me how you'd like to proceed; I can rearrange them into pull requests as you like.

There's also shrink.js which I'd like to put into the main line, but it's still a little glitchy.
https://github.com/alexch/ruby_notes/blob/master/shrink.js

### CODE REVIEW

**Comment by doolin** [comment]
I have to decide whether to fork Scott, or fork Alex. =(

**Comment by alexch** [comment]
It looks like Scott merged _most_ of my features, which is great news. 

There's still one feature that I've been using a lot, which is that every single H1 defines a new slide. (An earlier version of that feature did make it in, but it only works if there are no !SLIDE markers anywhere in the file. The new way's better :-))

Scott backed it out in commit 5f7d2b7, I presume because it messed with the formatting in some of his existing presos, which makes sense. For me, I find it makes it super easy to whip out a preso from an outline or vice versa. And I like being able to tell people "go read it on github" and having the .md file be mostly devoid of !SLIDE clutter.

I suppose I'll go reimplement it as a config option and submit a new pull request...

Dave, are you making !SLIDE-free slides?

Scott, are you finding yourself using # inside a slide, not just for the title? If so, what do you think of using ## (H2) instead?

**Comment by schacon** [comment]
hm, yeah i like the idea, but it needs to be configurable - it just wreaks havoc with a bunch of my presos - i'll look at your other PRs now

**Comment by doolin** [comment]
Alex, my last set was in Keynote, which I'm wanting showoff to replace. (Since latex/beamer/prosper is impractical). I'll catch up with you shortly in meatspace.

Scott, thanks for pulling Alex's commits.

**Pull request merged**
